# using port 3001 since alot of other stuff, node, etc.. typically runs on 3000
# sam local start-api -p 3001 -t localtemplate.yml
# sam local start-api -p 3001 -t localtemplate.yml  --skip-pull-image     (after initial runs)

# note: CodeURI element can be a .jar file, or path to the code extracted from a shaded jar  - using the Unarchiver

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  FloridaKeysAPI:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Sls-Vertx-Api
      Runtime: java8
      Timeout: 60
      CodeUri: target/sls-vertx-api-dev
      Handler: sls.vertx.api.ServiceLauncher::handleRequest
      Events: 
        Api: 
          Type: Api
          Properties: 
            Path: /users
            Method: GET
        Api2:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: GET
        Api3:
          Type: Api
          Properties:
            Path: /users
            Method: POST
        Api4:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: POST
        Api5:
          Type: Api
          Properties:
            Path: /data/{yearmonth}
            Method: GET
        Api6:
          Type: Api
          Properties:
            Path: /loaddata/{yearmonth}
            Method: GET