# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: floridakeys-api # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: java8

# you can add packaging information here
package:
  artifact: target/floridakeys-api-dev.jar

functions:
  users:
    handler: com.rodellison.serverless.VertxHandler
    events:
      - http:
          path: users
          method: get
          cors: true
      - http:
          path: users/{id}
          method: get
          cors: true
      - http:
          path: users
          method: post
          cors: true
      - http:
          path: users/{id}
          method: put
          cors: true
      - http:
          path: users/{id}
          method: delete
          cors: true


